server:
  port: 7788
  context-path: /bls
spring:
  application:
    name: BillListSystem
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-965z0z7s.bj.tencentcdb.com:10155/bill_list_system?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    url: jdbc:mysql://49.235.133.129:3306/bill_list_system?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    url: jdbc:mysql://127.0.0.1:3306/bill_list_system?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: bls&123@!
#    password: 123456
    druid:
      maxWait: 5000
      max-active: 500
      max-total: 500

#  redis:
#    host: 192.168.1.146
#    database: 0
#    port: 6379
#    timeout: 100000
#    pool:
#      max-idle: 10000
#      min-idle: 50

# 该配置节点为独立的节点，如果将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  type-aliases-package: com.chinaoly.Model  #注意：对应实体类的路径
  mapper-locations: classpath:**/mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径

logging:
  config: classpath:logback-spring.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 服务器存放文件地址
file:
  paths: /opt/billlistsystem/file/wordAndExecl/
  shoseTemplate: shoseTemplate.xlsx
  ticketTemplate: ticketTemplate.xlsx
  wordTemplate: wordTemplate.docx

# word转pdf配置
#jodconverter:
#  local:
#    enabled: true
#      服务器
##    office-home: /opt/openoffice4
#     本地
#    office-home: /Applications/OpenOffice.app/Contents
#    max-tasks-per-process: 10
#    port-numbers: 8100
